//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by APIGen.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDM_CUSTOM_FILE                 0x0011
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_APIGEN_DIALOG               102
#define IDS_CUSTOM_FILE                 102
#define IDR_HTML_DEPLOYPARAMS           103
#define IDR_HTML_DEPLOYPARAMS1          105
#define IDR_HTML_XML5250                106
#define IDR_MAINFRAME                   128
#define IDD_DEPLOY_PARAMS               130
#define IDD_XML_3270                    131
#define IDD_XML_5250                    132
#define IDD_XML_VT                      133
#define IDD_AIRVM_3270                  134
#define IDD_AIRVM_UTS                   135
#define IDD_AIRVM_T27                   136
#define IDD_VHI_NEWSTRINGMAP            137
#define IDD_VHI_NEWSTRINGLIST           138
#define IDD_PERFORCE_GLOBALS            139
#define IDD_DIALOG1                     140
#define IDD_CUSTOM_ACTIONS              140
#define IDD_DIALOG2                     141
#define IDDLG_WIX_DLG                   141
#define IDLIST_API_CHOICE               1001
#define IDLIST_LANGUAGE_CHOICE          1002
#define IDLIST_FUNCTION_CHOICE          1003
#define IDCHECK_WRITE_SOURCE            1004
#define IDBUTTON_APPEND_SOURCE          1005
#define IDC_EDIT2                       1006
#define IDEDIT_STRING_LENGTH            1006
#define IDEDIT_CUSTOM_FOOTER            1006
#define IDEDIT_DEPLOY_PASSWORD          1006
#define IDEDIT_XML_3270_PORTNUMBER      1006
#define IDEDIT_AIRVMUTS_TRANSPORT       1006
#define IDEDIT_VHI_STRINGMAP_VALUE      1006
#define IDEDIT_PERFORCE_CLIENT_PWD      1006
#define IDEDIT_CUSTOMACTION_FUNCNAME    1006
#define IDEDIT_WIX_BMP_ID               1006
#define IDBUTTON_GENERATE_SOURCE        1007
#define IDLIST_OUTPUT_TEXT              1008
#define IDCHECK_PROMPT_FOR_VALUES       1009
#define IDBUTTON_FINALIZE               1010
#define IDEDIT_STRING                   1011
#define IDEDIT_RETURN_CODE              1012
#define IDBUTTON_NEW_PROJECT            1013
#define IDBUTTON_SAVE_TO_FILE           1014
#define IDSTATIC_STRING                 1015
#define IDSTATIC_STRINGLENGTH           1016
#define IDSTATIC_RETURNCODE             1017
#define IDSTATIC_ROW                    1018
#define IDSTATIC_COLUMN                 1019
#define IDEDIT_ROW                      1021
#define IDEDIT_COLUMN                   1022
#define IDSTATIC_LENGTH                 1023
#define IDEDIT_LENGTH                   1024
#define IDSTATIC_PARAMETER_GROUP        1025
#define IDSTATIC_NO_PARAMETERS          1026
#define IDSTATIC_PUTSTRING              1028
#define IDEDIT_PUTSTRING                1029
#define IDSTATIC_MOVE_ROWS              1030
#define IDSTATIC_COLUMNS_MOVED          1031
#define IDSTATIC_TIMEOUT                1032
#define IDSTATIC_KEYS                   1033
#define IDCHECK_PROCESS                 1034
#define IDEDIT_TIMEOUT                  1035
#define IDEDIT_USERKEYS                 1036
#define IDSTATIC_SETTLETIME             1037
#define IDEDIT_SETTLE_TIME              1038
#define IDSTATIC_CLOSEOPTION            1039
#define IDEDIT_CLOSE_OPTION             1040
#define IDEDIT_FILETRANSFER_SCHEME      1041
#define IDSTATIC_FT_SCHEME              1042
#define IDBUTTON_FT_SCHEME_NAME         1043
#define IDCHECK_SET_FT_                 1044
#define IDSTATIC_KEYBOARD_MAP           1048
#define IDEDIT_KEYBOARD_MAP             1049
#define IDBUTTON_BROWSE_KEYMAP          1050
#define IDCHECK_KEYBOARD_MAP            1051
#define IDLIST_FIELDTYPE                1052
#define IDSTATIC_FIELDTYPE              1053
#define IDLIST_MNEMONIC                 1054
#define IDSTATIC_MNEMONIC               1055
#define IDCSTATIC_HOSTCHARSET           1056
#define IDSTATIC_HOSTCODEPAGE           1057
#define IDSTATIC_SCREENMODEL            1058
#define IDLIST_SCREENMODEL              1059
#define IDSTATIC_IDLETIME               1060
#define IDSTATIC_LANGUAGE               1061
#define IDCHECK_LANGUAGE                1062
#define IDCCHECK_LOCALMODE              1063
#define IDCHECK_SETMENU                 1064
#define IDCHECK_SET_SESS_QUIET          1065
#define IDSTATIC_PC_FILENAME            1066
#define IDEDIT_PC_FILENAME              1067
#define IDEDIT_HOSTFILENAME             1068
#define IDSTATIC_HOST_FILENAME          1069
#define IDBUTTON_FT_FILENAME            1070
#define IDCHECK_SHOW_FT_STATUS          1071
#define IDCHECK_VISIBLE                 1072
#define IDCCHECK_CONTINUOUS_WAIT        1073
#define IDSTATIC_HEIGHT                 1074
#define IDSTATIC_WIDTH                  1075
#define IDCHECK_HEIGHT                  1076
#define IDCHECK_WIDTH                   1077
#define IDEDIT_HEIGHT                   1078
#define IDEDIT_WIDTH                    1079
#define IDLIST_WINDOW_STATE             1080
#define IDSTATIC_WINDOWSTATE            1081
#define IDCHECK_SET_WINDOWSTATE         1082
#define IDSTATIC_SESSIONFILE_NAME       1083
#define IDEDIT_SESSION_FILENAME         1084
#define IDBUTTON_SESSION_FILENAME       1085
#define IDCHECK_SETTIMEOUT              1086
#define IDSTATIC_CUSTOM_HEADER          1088
#define IDSTATIC_CUSTOM_FOOTER          1089
#define IDEDIT_HEADER_FILENAME          1090
#define IDBUTTON_HEADER                 1091
#define IDBUTTON_FOOTER                 1092
#define IDSTATIC_SOCKS_PORT             1095
#define IDSTATIC_SOCKS_ADDRESS          1096
#define IDSTATIC_TELNET_PORT            1097
#define IDSTATIC_TELNET_ADDRESS         1098
#define IDCHECK_FILE_INSERT             1099
#define IDBUTTON_HELP                   1100
#define IDC_LIST_TERMINAL_TYPE          1101
#define IDLIST_TERMINAL_TYPE            1101
#define IDEDIT_ARGUMENT1                1102
#define IDEDIT_ARGUMENT2                1103
#define IDEDIT_ARGUMENT3                1104
#define IDEDIT_ARGUMENT4                1105
#define IDC_EDIT3                       1106
#define IDEDIT_ARGUMENT5                1106
#define IDEDIT_DEPLOY_CHANNEL           1106
#define IDEDIT_PERFORCE_HOST            1106
#define IDEDIT_WIX_BMP_FILE             1106
#define IDC_LIST1                       1107
#define IDLIST_VHI_STRINGMAPPAIRS       1107
#define IDCHECK_PASSIVE_MODE            1108
#define IDEDIT_ARGUMENT6                1109
#define IDSTATIC_STRING4                1110
#define IDSTATIC_STRING5                1111
#define IDLIST_TRANSFER_TYPE            1112
#define IDLIST_FILE_EXISTS              1113
#define IDCHECK_EABs_ENABLED            1114
#define IDSTATIC_TERMINAL_TYPE          1115
#define IDEDIT_ARGUMENT7                1116
#define IDSTATIC_6                      1117
#define IDEDIT_ARGUMENT8                1118
#define IDEDIT_ARGUMENT9                1119
#define IDEDIT_ARGUMENT10               1120
#define IDEDIT_ARGUMENT11               1121
#define IDEDIT_ARGUMENT12               1122
#define IDEDIT_ARGUMENT13               1123
#define IDEDIT_ARGUMENT14               1124
#define IDSTATICSTRING8                 1125
#define IDSTATICSTRING9                 1126
#define IDSTATICSTRING10                1127
#define IDSTATICSTRING11                1128
#define IDSTATICSTRING12                1129
#define IDSTATICSTRING13                1130
#define IDSTATICSTRING14                1131
#define IDSTATICSTRING7                 1132
#define IDEDIT_DEPLOY_URL               1133
#define IDEDIT_DEPLOY_USERNAME          1134
#define IDLIST_DEPLOY_LANGUAGE          1135
#define IDEDIT_DEPLOY_PRESENTATION_ID   1136
#define IDEDIT_DEPLOY_APPLICATION_MODE  1137
#define IDLIST_PARAMS_1                 1138
#define IDCHECK_PARAM1                  1139
#define IDLIST_PARAMS2                  1140
#define IDC_CHECK2                      1141
#define IDCHECK_PARAM2                  1141
#define IDCHECK_XML_5250_DESTRUCIVE_BACKSPACE 1141
#define IDCHECK_XML_VT_INITNEGOTIATION  1141
#define IDCHECK_PERFORCE_GLOBAL_PWD     1141
#define IDLIST_PARAMS3                  1142
#define IDLIST_PARAMS4                  1143
#define IDC_LIST3                       1144
#define IDLIST_PARAMS5                  1144
#define IDMULTILIST_PARAMS1             1145
#define IDMULTILIST_PARAMS2             1146
#define IDMULTILIST_PARAMS3             1147
#define IDC_LIST4                       1148
#define IDMULTILIST_PARAMS4             1148
#define IDC_CHECK1                      1149
#define IDCHECK_PARAM3                  1149
#define IDCHECK_XML_3270_LPENABLED      1149
#define IDCHECK_XML_5250_NUMERICFIELDOVERRIDE 1149
#define IDCHECK_XML_VT_LOCALMODE        1149
#define IDCHECK_ADDNEWSTRINGMAP         1149
#define IDCHECK_ADDNEWSTRINGLIST        1149
#define IDCHECK_PERFORCE_GLOBAL_CLIENT  1149
#define IDEDIT_XML_3270_HOSTNAME        1150
#define IDLIST_XML_3270_TEXTCASE        1151
#define IDLIST_XML_3270_BACKSPACE       1152
#define IDC_EDIT4                       1153
#define IDEDIT_XML_3270_XLATEFILE       1153
#define IDEDIT_PERFORCE_PORT            1153
#define IDEDIT_WIX_DLG_TITLE            1153
#define IDEDIT_XML_5250_HOSTNAME        1154
#define IDEDIT_XML_5250_PORTNUMBER      1155
#define IDLIST_XML_5250_TEXTCASE        1156
#define IDLIST_XML_5250_ATTRIBUTE_STYLE 1157
#define IDEDIT_XML_5250_XLATEFILE       1158
#define IDEDIT_XML_VT_HOSTNAME          1159
#define IDEDIT_XML_VT_PORTNUMBER        1160
#define IDCHECK_XML_VT_NEGOTIATE_BINARY 1161
#define IDCHECK_XML_VT_AUTOWRAP         1162
#define IDEDIT_XML_VT_COLUMNS           1163
#define IDEDIT_XML_VT_TABCOLUMNS        1163
#define IDEDIT_AIRVMUTS_HOSTADDR        1164
#define IDEDIT_AIRVM3270_HOSTADDR       1165
#define IDEDIT_AIRVMUTS_ENVNAME         1166
#define IDEDIT_AIRVMT27_HOSTADDR        1167
#define IDEDIT_AIRVMT27_STATIONID       1168
#define IDC_LIST2                       1169
#define IDLISTCTRL_APIGEN_ABOUT         1169
#define IDLIST_VHI_STRINGLIST           1169
#define IDEDIT_VHI_STRINGMAP_NAME       1170
#define IDBUTTON_VHI_STRINGMAP_ADD      1171
#define IDC_BUTTON2                     1172
#define IDBUTTON_VHI_STRINGMAP_REMOVE   1172
#define IDBUTTON_VHI_STRINGLIST_REMOVE  1172
#define IDCHECK_PARAM4                  1173
#define IDEDIT_VHI_STRINGLIST_STRING    1174
#define IDC_BUTTON1                     1175
#define IDBUTTON_VHI_STRINGLIST_ADD     1175
#define IDBUTTON_WIX_BMP                1175
#define IDEDIT_PERFORCE_CLIENT_OVERRIDE 1176
#define IDCHECK_PERFORCE_PYTHON_DICTIONARIES 1177
#define IDCHECK_PERFORCE_HOST           1178
#define IDCHECK_PERFORCE_PORT           1179
#define IDCHECK_PERFORCE_PASSWORD       1180
#define IDCHECK_PERFORCE_PREPEND        1181
#define IDCHECK_PERFORCE_USERNAME       1182
#define IDCHECK_PERFORCE_INPUT_FILE     1183
#define IDCHECK_PERFORCE_CHARACTER_SET  1184
#define IDCHECK_PERFORCE_VERSION        1185
#define IDCHECK_PERFORCE_DISPLAY_HELP   1186
#define IDEDIT_PERFORCE_PASSWORD        1187
#define IDEDIT_PERFORCE_USERNAME        1188
#define IDEDIT_PERFORCE_FILENAME        1189
#define IDC_EDIT8                       1190
#define IDEDIT_PERFORCE_CHARSET         1190
#define IDEDIT_CUSTOMACTION_CLASS       1191
#define IDEDIT_WIX_DLG_ID               1192

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1193
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
